---
   # Postgresql Configuration/Setup
   # Deepak Shenoy, November 12, 2015
   #
   - hosts: all
     sudo: true
     vars: 
       #
       # Common variables
       #
       download_folder: "/opt"
       
       # 
       # Postgresql files
       #
       postg_rpm2: "postgresql94-9.4.5-1PGDG.rhel7.x86_64.rpm"
       postg_rpm3: "postgresql94-contrib-9.4.5-1PGDG.rhel7.x86_64.rpm"
       postg_rpm1: "postgresql94-libs-9.4.5-1PGDG.rhel7.x86_64.rpm"
       postg_rpm4: "postgresql94-server-9.4.5-1PGDG.rhel7.x86_64.rpm"
       
     
     roles:
        - common
        - database
        